### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mgp25** [checkwa/API-CheckWa#1]
Hello,

You are using [Chat API](https://github.com/mgp25/Chat-API), so you need to add credits in the readme. Although you are using here a REST API, it's very easy to know that Chat API/yowsup is being used.

In the other hand, [http://www.checkwa.com](http://www.checkwa.com) doesnt use any security/encryption, so the credentials of the users can be compromised.

Best regards

**Comment by AppMessenger** [comment]
I can`t check phone number in this web cite. Is it working?
